version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - postgres
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  postgres:
    image: postgres:14-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root